"""empty message

Revision ID: ed7842a1ef4a
Revises: fba6f9dda09a
Create Date: 2019-10-28 12:15:18.867055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed7842a1ef4a'
down_revision = 'fba6f9dda09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['messenger_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
