"""empty message

Revision ID: fba6f9dda09a
Revises: 2ce50286c1bf
Create Date: 2019-10-28 12:09:37.662878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fba6f9dda09a'
down_revision = '2ce50286c1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messenger_user',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id')
    )
    op.alter_column('product', 'category_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'category_id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               nullable=True)
    op.drop_table('messenger_user')
    # ### end Alembic commands ###
